server:
    shutdown: "graceful"

spring:
    lifecycle:
        timeout-per-shutdown-phase: "20s"

camel:
    health:
        enabled: true
    server-port: 5000
    springboot:
        main-run-controller: true
    dataformat:
        json-jackson:
            auto-discover-object-mapper: true

management:
    endpoint:
        health:
            show-details: always
            group:
                liveness:
                    include:
                        - camelHealth
                        # zeebeClient will not get included in the liveness state
                readiness:
                    include:
                        - camelHealth
                        - zeebeClient

baasflow:
    events:
        disabled: "false"
        kafka:
            msk: "true"
            brokers: "b-3.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098,b-2.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098,b-1.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098"
            topic: ${COMMONS_EVENTS_AUDIT_KAFKA_TOPIC}
            connection-timeout-ms: 1000
            request-timeout-ms: 1000
            retries-count: 3
        channels:
            audit:
                topic: "auditlog"

dfspids: "DFSPID"

fineract:
    api-url: ${FINERACT_URL}
    datatable-query-api: "/datatables/dt_client_account_mapping/query"
    column-filter: "iban"
    result-columns: "conversion_account_id,disposal_account_id,internal_account_id"
    internal-id-column: "internal_account_id"
    incoming-money-api: "/savingsaccounts/"
    locale: "en"

zeebe:
    client:
        worker:
            max-jobs-active: 100
            threads: 100

ams:
    local:
        server-cert-check: false
        enabled: false